FROM openjdk:11-jre-slim

RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools@12.4.0

WORKDIR /app

# The CMD is now fully controlled by docker-compose.yml
